# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 630)
        mainWindow.setMinimumSize(QtCore.QSize(600, 630))
        mainWindow.setMaximumSize(QtCore.QSize(600, 630))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/zk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("")
        mainWindow.setIconSize(QtCore.QSize(25, 24))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet(".QWidget{\n"
"    \n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-2, 26, 606, 581))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"    font: 75 14pt \"微软雅黑\";\n"
"    border:none;\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab {\n"
"    font: 75 13pt \"微软雅黑\";        \n"
"    color: rgb(255, 255, 255);\n"
"    width:160px;                    \n"
"    height:18;                     \n"
"    margin-top:5px;    \n"
"    background:rgb(150, 75, 112);\n"
"    padding:20px;\n"
"    margin-right:0px;\n"
"    border-right:1px solid qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"\n"
"    \n"
"}\n"
"QTabWidget::pane {\n"
"    border: 0px solid black;\n"
"    border-radius:7px;\n"
"    position: absolute;\n"
"    top: -1em;\n"
"}    \n"
"QTabBar::tab:selected{\n"
" background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(200, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
" \n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(45, 45))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(345, 44, 251, 481))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(535, 13, 60, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(345, 24, 61, 18))
        self.label_2.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 321, 257))
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(5000, 5000))
        self.frame_2.setStyleSheet(".QFrame{\n"
"   background-color: rgb(255, 255, 255);\n"
"   border:0px;\n"
"   border-radius:12px;\n"
"   color:white;\n"
"   border: 6px solid qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"   }\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"color: rgb(0, 0, 0);\n"
"    color: rgb(127, 127, 127);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_lian = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_lian.setEnabled(False)
        self.lineEdit_lian.setGeometry(QtCore.QRect(120, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_lian.setFont(font)
        self.lineEdit_lian.setStyleSheet("")
        self.lineEdit_lian.setText("")
        self.lineEdit_lian.setObjectName("lineEdit_lian")
        self.lineEdit_jieguo = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_jieguo.setEnabled(False)
        self.lineEdit_jieguo.setGeometry(QtCore.QRect(120, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_jieguo.setFont(font)
        self.lineEdit_jieguo.setStyleSheet("")
        self.lineEdit_jieguo.setText("")
        self.lineEdit_jieguo.setObjectName("lineEdit_jieguo")
        self.lineEdit_youwu = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_youwu.setEnabled(False)
        self.lineEdit_youwu.setGeometry(QtCore.QRect(220, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_youwu.setFont(font)
        self.lineEdit_youwu.setStyleSheet("")
        self.lineEdit_youwu.setText("")
        self.lineEdit_youwu.setObjectName("lineEdit_youwu")
        self.lineEdit_kaimen = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_kaimen.setEnabled(False)
        self.lineEdit_kaimen.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_kaimen.setFont(font)
        self.lineEdit_kaimen.setStyleSheet("")
        self.lineEdit_kaimen.setText("")
        self.lineEdit_kaimen.setObjectName("lineEdit_kaimen")
        self.lineEdit_pingbi = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_pingbi.setEnabled(False)
        self.lineEdit_pingbi.setGeometry(QtCore.QRect(10, 210, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_pingbi.setFont(font)
        self.lineEdit_pingbi.setStyleSheet("")
        self.lineEdit_pingbi.setText("")
        self.lineEdit_pingbi.setObjectName("lineEdit_pingbi")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 470, 281, 16))
        self.groupBox.setStyleSheet("border:none")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_zk = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_zk.setGeometry(QtCore.QRect(10, 0, 71, 16))
        self.radioButton_zk.setStyleSheet("\n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.radioButton_zk.setObjectName("radioButton_zk")
        self.radioButton_csj = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_csj.setGeometry(QtCore.QRect(160, 0, 81, 16))
        self.radioButton_csj.setStyleSheet("\n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.radioButton_csj.setObjectName("radioButton_csj")
        self.pushButton_jiepingbi = QtWidgets.QPushButton(self.tab)
        self.pushButton_jiepingbi.setGeometry(QtCore.QRect(100, 310, 75, 23))
        self.pushButton_jiepingbi.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_jiepingbi.setObjectName("pushButton_jiepingbi")
        self.pushButton_pingbi = QtWidgets.QPushButton(self.tab)
        self.pushButton_pingbi.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.pushButton_pingbi.setStyleSheet("QPushButton{  \n"
"border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"color: rgb(0,0,0);    \n"
"border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{  \n"
"    ;\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_pingbi.setObjectName("pushButton_pingbi")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 490, 321, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.lineEdit_fasong = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_fasong.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)")
        self.lineEdit_fasong.setObjectName("lineEdit_fasong")
        self.horizontalLayout.addWidget(self.lineEdit_fasong)
        self.pushButton_fasong = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_fasong.setMinimumSize(QtCore.QSize(60, 28))
        self.pushButton_fasong.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_fasong.setObjectName("pushButton_fasong")
        self.horizontalLayout.addWidget(self.pushButton_fasong)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/js.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.dakai_plc = QtWidgets.QPushButton(self.tab_2)
        self.dakai_plc.setGeometry(QtCore.QRect(60, 350, 71, 31))
        self.dakai_plc.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.dakai_plc.setObjectName("dakai_plc")
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setGeometry(QtCore.QRect(20, 110, 169, 33))
        self.label_51.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial Rounded MT Bold\";\n"
"border: 0.5px solid ;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label_51.setObjectName("label_51")
        self.save_buton = QtWidgets.QPushButton(self.tab_2)
        self.save_buton.setGeometry(QtCore.QRect(520, 490, 71, 31))
        self.save_buton.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.save_buton.setObjectName("save_buton")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 151, 171, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_52.setMinimumSize(QtCore.QSize(60, 25))
        self.label_52.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 0, 0, 1, 1)
        self.comboBox_com = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_com.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_com.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_com.setObjectName("comboBox_com")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.gridLayout.addWidget(self.comboBox_com, 0, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_53.setMinimumSize(QtCore.QSize(60, 25))
        self.label_53.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 1, 0, 1, 1)
        self.comboBox_botelv = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_botelv.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_botelv.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_botelv.setObjectName("comboBox_botelv")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.gridLayout.addWidget(self.comboBox_botelv, 1, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_54.setMinimumSize(QtCore.QSize(60, 25))
        self.label_54.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 2, 0, 1, 1)
        self.comboBox_jiaoyan = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_jiaoyan.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_jiaoyan.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_jiaoyan.setObjectName("comboBox_jiaoyan")
        self.comboBox_jiaoyan.addItem("")
        self.comboBox_jiaoyan.addItem("")
        self.comboBox_jiaoyan.addItem("")
        self.comboBox_jiaoyan.addItem("")
        self.gridLayout.addWidget(self.comboBox_jiaoyan, 2, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_55.setMinimumSize(QtCore.QSize(60, 25))
        self.label_55.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 3, 0, 1, 1)
        self.comboBox_shujuwei = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_shujuwei.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_shujuwei.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_shujuwei.setObjectName("comboBox_shujuwei")
        self.comboBox_shujuwei.addItem("")
        self.comboBox_shujuwei.addItem("")
        self.comboBox_shujuwei.addItem("")
        self.comboBox_shujuwei.addItem("")
        self.gridLayout.addWidget(self.comboBox_shujuwei, 3, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_56.setMinimumSize(QtCore.QSize(60, 25))
        self.label_56.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 4, 0, 1, 1)
        self.comboBox_tingzhiwei = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_tingzhiwei.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_tingzhiwei.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image:url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_tingzhiwei.setObjectName("comboBox_tingzhiwei")
        self.comboBox_tingzhiwei.addItem("")
        self.comboBox_tingzhiwei.addItem("")
        self.comboBox_tingzhiwei.addItem("")
        self.gridLayout.addWidget(self.comboBox_tingzhiwei, 4, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(23, 20, 251, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_16.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_16.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.comboBox_kehu = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_kehu.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_kehu.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{ \n"
" image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:35px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_kehu.setObjectName("comboBox_kehu")
        self.comboBox_kehu.addItem("")
        self.comboBox_kehu.addItem("")
        self.comboBox_kehu.addItem("")
        self.comboBox_kehu.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_kehu, 0, 1, 1, 1)
        self.pushButton_lian = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_lian.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton_lian.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_lian.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_lian.setObjectName("pushButton_lian")
        self.gridLayout_2.addWidget(self.pushButton_lian, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(70, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_4.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.pushButton_duan = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_duan.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton_duan.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_duan.setObjectName("pushButton_duan")
        self.gridLayout_2.addWidget(self.pushButton_duan, 1, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setGeometry(QtCore.QRect(290, 23, 91, 25))
        self.label_50.setMinimumSize(QtCore.QSize(80, 25))
        self.label_50.setMaximumSize(QtCore.QSize(110, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                  stop:0 rgb(150, 75, 112),stop:0.5 rgb(255,             255, 255),stop:1 rgb(150, 75, 112));\n"
"color: rgb(0, 0, 0);\n"
"font: 75 10pt \"微软雅黑\";\n"
"border: 0.5px solid ;\n"
"\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;")
        self.label_50.setObjectName("label_50")
        self.lineEdit_log = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_log.setGeometry(QtCore.QRect(390, 23, 200, 25))
        self.lineEdit_log.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_log.setMaximumSize(QtCore.QSize(220, 25))
        self.lineEdit_log.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)")
        self.lineEdit_log.setObjectName("lineEdit_log")
        self.pushButton_shanchu = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_shanchu.setGeometry(QtCore.QRect(350, 350, 71, 31))
        self.pushButton_shanchu.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_shanchu.setObjectName("pushButton_shanchu")
        self.pushButton_xieru = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_xieru.setGeometry(QtCore.QRect(240, 350, 71, 31))
        self.pushButton_xieru.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_xieru.setObjectName("pushButton_xieru")
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(250, 110, 169, 33))
        self.label_57.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial Rounded MT Bold\";\n"
"border: 0.5px solid ;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label_57.setObjectName("label_57")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(220, 150, 221, 191))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_4.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_5.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_5.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_5, 4, 1, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/sz_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/bz_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon3, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 601, 31))
        self.frame.setStyleSheet("background:rgb(150, 75, 112)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setGeometry(QtCore.QRect(570, 10, 25, 25))
        self.pushButton_close.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setStyleSheet("QPushButton{ border:none}\n"
"QPushButton:hover{  \n"
"    ;\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed{  \n"
"    ;\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/closee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon4)
        self.pushButton_close.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(540, 10, 25, 25))
        self.pushButton_min.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_min.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_min.setStyleSheet("QPushButton{ border:none}\n"
"\n"
"QPushButton:hover{\n"
"    ;\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 85, 255);\n"
"}\n"
"QPushButton:pressed{  \n"
"    ;\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.pushButton_min.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/minn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon5)
        self.pushButton_min.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(5, 5, 25, 25))
        self.pushButton_2.setStyleSheet("border:none")
        self.pushButton_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/zd_0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(35, 7, 31, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(150, 75, 112);")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actiondakaipeizhiwenjian = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Picturere/Picture/right2.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actiondakaipeizhiwenjian.setIcon(icon7)
        self.actiondakaipeizhiwenjian.setObjectName("actiondakaipeizhiwenjian")
        self.actiondakaipeizhiwenjian_2 = QtWidgets.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Picturere/Picture/square_add.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actiondakaipeizhiwenjian_2.setIcon(icon8)
        self.actiondakaipeizhiwenjian_2.setObjectName("actiondakaipeizhiwenjian_2")
        self.actionlianjixieshou_I = QtWidgets.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Basilisk.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionlianjixieshou_I.setIcon(icon9)
        self.actionlianjixieshou_I.setObjectName("actionlianjixieshou_I")
        self.actionlianPlc_T = QtWidgets.QAction(mainWindow)
        self.actionlianPlc_T.setIcon(icon9)
        self.actionlianPlc_T.setPriority(QtWidgets.QAction.HighPriority)
        self.actionlianPlc_T.setObjectName("actionlianPlc_T")
        self.actioncaozuoPLC_O = QtWidgets.QAction(mainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Djinni.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actioncaozuoPLC_O.setIcon(icon10)
        self.actioncaozuoPLC_O.setObjectName("actioncaozuoPLC_O")
        self.actionCanshushezhi_P = QtWidgets.QAction(mainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Sorceress.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionCanshushezhi_P.setIcon(icon11)
        self.actionCanshushezhi_P.setObjectName("actionCanshushezhi_P")
        self.actionjinzhi_N = QtWidgets.QAction(mainWindow)
        self.actionjinzhi_N.setObjectName("actionjinzhi_N")
        self.actionxunyu_Y = QtWidgets.QAction(mainWindow)
        self.actionxunyu_Y.setObjectName("actionxunyu_Y")
        self.actiondakaishujukufuwuqi = QtWidgets.QAction(mainWindow)
        self.actiondakaishujukufuwuqi.setObjectName("actiondakaishujukufuwuqi")
        self.actionguanbishujukufuwuqi = QtWidgets.QAction(mainWindow)
        self.actionguanbishujukufuwuqi.setObjectName("actionguanbishujukufuwuqi")
        self.actionlianjieshujuku_L = QtWidgets.QAction(mainWindow)
        self.actionlianjieshujuku_L.setObjectName("actionlianjieshujuku_L")
        self.actionduankaishujuku_C = QtWidgets.QAction(mainWindow)
        self.actionduankaishujuku_C.setObjectName("actionduankaishujuku_C")
        self.actionpanduan_Y = QtWidgets.QAction(mainWindow)
        self.actionpanduan_Y.setObjectName("actionpanduan_Y")
        self.actionbupanduan_N = QtWidgets.QAction(mainWindow)
        self.actionbupanduan_N.setObjectName("actionbupanduan_N")
        self.actionyicitongguo_O = QtWidgets.QAction(mainWindow)
        self.actionyicitongguo_O.setObjectName("actionyicitongguo_O")
        self.actionchankandangqianzhuangtai_S = QtWidgets.QAction(mainWindow)
        self.actionchankandangqianzhuangtai_S.setObjectName("actionchankandangqianzhuangtai_S")
        self.actionjilu_R = QtWidgets.QAction(mainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Valkyrie.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionjilu_R.setIcon(icon12)
        self.actionjilu_R.setObjectName("actionjilu_R")
        self.actionshegnchengdejieguo_G = QtWidgets.QAction(mainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Earth Elemental.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionshegnchengdejieguo_G.setIcon(icon13)
        self.actionshegnchengdejieguo_G.setObjectName("actionshegnchengdejieguo_G")
        self.actionpeizhicanshulujing_M = QtWidgets.QAction(mainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Picturere/Picture/rightdown.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionpeizhicanshulujing_M.setIcon(icon14)
        self.actionpeizhicanshulujing_M.setObjectName("actionpeizhicanshulujing_M")
        self.actionzhegnchangshenchan_N = QtWidgets.QAction(mainWindow)
        self.actionzhegnchangshenchan_N.setObjectName("actionzhegnchangshenchan_N")
        self.actionshouliaomoshi_C = QtWidgets.QAction(mainWindow)
        self.actionshouliaomoshi_C.setObjectName("actionshouliaomoshi_C")
        self.actionshi_Y = QtWidgets.QAction(mainWindow)
        self.actionshi_Y.setObjectName("actionshi_Y")
        self.actionfou_N = QtWidgets.QAction(mainWindow)
        self.actionfou_N.setObjectName("actionfou_N")
        self.actionzhongkongjima_P = QtWidgets.QAction(mainWindow)
        self.actionzhongkongjima_P.setObjectName("actionzhongkongjima_P")
        self.actionchongxinsaoma_I = QtWidgets.QAction(mainWindow)
        self.actionchongxinsaoma_I.setObjectName("actionchongxinsaoma_I")
        self.actionqiyong_U = QtWidgets.QAction(mainWindow)
        self.actionqiyong_U.setObjectName("actionqiyong_U")
        self.actionjinyong_N = QtWidgets.QAction(mainWindow)
        self.actionjinyong_N.setObjectName("actionjinyong_N")
        self.actionchakanbangzhu_V = QtWidgets.QAction(mainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Wizard.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionchakanbangzhu_V.setIcon(icon15)
        self.actionchakanbangzhu_V.setObjectName("actionchakanbangzhu_V")
        self.actioncaozuojixies = QtWidgets.QAction(mainWindow)
        self.actioncaozuojixies.setObjectName("actioncaozuojixies")
        self.actionxunhuanjieshoujxs = QtWidgets.QAction(mainWindow)
        self.actionxunhuanjieshoujxs.setObjectName("actionxunhuanjieshoujxs")
        self.actionshoudongPLC = QtWidgets.QAction(mainWindow)
        self.actionshoudongPLC.setObjectName("actionshoudongPLC")
        self.actionmianbanxieru = QtWidgets.QAction(mainWindow)
        self.actionmianbanxieru.setObjectName("actionmianbanxieru")
        self.actiondakaiwangkou = QtWidgets.QAction(mainWindow)
        self.actiondakaiwangkou.setObjectName("actiondakaiwangkou")
        self.actionwangkoufasong = QtWidgets.QAction(mainWindow)
        self.actionwangkoufasong.setObjectName("actionwangkoufasong")
        self.actionjiechuPlc = QtWidgets.QAction(mainWindow)
        self.actionjiechuPlc.setObjectName("actionjiechuPlc")

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "    终端"))
        self.textEdit.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("mainWindow", "清屏"))
        self.label_2.setText(_translate("mainWindow", "实时通讯"))
        self.lineEdit_lian.setPlaceholderText(_translate("mainWindow", "未联机"))
        self.lineEdit_jieguo.setPlaceholderText(_translate("mainWindow", "测试中"))
        self.lineEdit_youwu.setPlaceholderText(_translate("mainWindow", "有/无料"))
        self.lineEdit_kaimen.setPlaceholderText(_translate("mainWindow", "门状态"))
        self.lineEdit_pingbi.setPlaceholderText(_translate("mainWindow", "未屏蔽"))
        self.radioButton_zk.setText(_translate("mainWindow", "到中控"))
        self.radioButton_csj.setText(_translate("mainWindow", "到测试机"))
        self.pushButton_jiepingbi.setText(_translate("mainWindow", "解除屏蔽"))
        self.pushButton_pingbi.setText(_translate("mainWindow", "屏蔽"))
        self.label_24.setText(_translate("mainWindow", " 内容："))
        self.pushButton_fasong.setText(_translate("mainWindow", "发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "实时监控"))
        self.dakai_plc.setText(_translate("mainWindow", "打开串口"))
        self.label_51.setText(_translate("mainWindow", "           串口参数:"))
        self.save_buton.setText(_translate("mainWindow", "保存配置"))
        self.label_52.setText(_translate("mainWindow", " 串口号:"))
        self.comboBox_com.setPlaceholderText(_translate("mainWindow", "COM选择"))
        self.comboBox_com.setItemText(0, _translate("mainWindow", "COM1"))
        self.comboBox_com.setItemText(1, _translate("mainWindow", "COM2"))
        self.comboBox_com.setItemText(2, _translate("mainWindow", "COM3"))
        self.comboBox_com.setItemText(3, _translate("mainWindow", "COM4"))
        self.comboBox_com.setItemText(4, _translate("mainWindow", "COM5"))
        self.comboBox_com.setItemText(5, _translate("mainWindow", "COM6"))
        self.comboBox_com.setItemText(6, _translate("mainWindow", "COM7"))
        self.comboBox_com.setItemText(7, _translate("mainWindow", "COM8"))
        self.comboBox_com.setItemText(8, _translate("mainWindow", "COM9"))
        self.label_53.setText(_translate("mainWindow", " 波特率:"))
        self.comboBox_botelv.setItemText(0, _translate("mainWindow", "9600"))
        self.comboBox_botelv.setItemText(1, _translate("mainWindow", "14400"))
        self.comboBox_botelv.setItemText(2, _translate("mainWindow", "19200"))
        self.comboBox_botelv.setItemText(3, _translate("mainWindow", "115200"))
        self.label_54.setText(_translate("mainWindow", " 校验位:"))
        self.comboBox_jiaoyan.setItemText(0, _translate("mainWindow", "E"))
        self.comboBox_jiaoyan.setItemText(1, _translate("mainWindow", "N"))
        self.comboBox_jiaoyan.setItemText(2, _translate("mainWindow", "O"))
        self.comboBox_jiaoyan.setItemText(3, _translate("mainWindow", "S"))
        self.label_55.setText(_translate("mainWindow", " 数据位:"))
        self.comboBox_shujuwei.setItemText(0, _translate("mainWindow", "7"))
        self.comboBox_shujuwei.setItemText(1, _translate("mainWindow", "5"))
        self.comboBox_shujuwei.setItemText(2, _translate("mainWindow", "6"))
        self.comboBox_shujuwei.setItemText(3, _translate("mainWindow", "8"))
        self.label_56.setText(_translate("mainWindow", " 停止位:"))
        self.comboBox_tingzhiwei.setItemText(0, _translate("mainWindow", "1"))
        self.comboBox_tingzhiwei.setItemText(1, _translate("mainWindow", "1.5"))
        self.comboBox_tingzhiwei.setItemText(2, _translate("mainWindow", "2"))
        self.label_16.setText(_translate("mainWindow", " 客户端地址"))
        self.comboBox_kehu.setItemText(0, _translate("mainWindow", "192.168.0.1"))
        self.comboBox_kehu.setItemText(1, _translate("mainWindow", "192.168.0.2"))
        self.comboBox_kehu.setItemText(2, _translate("mainWindow", "192.168.0.3"))
        self.comboBox_kehu.setItemText(3, _translate("mainWindow", "192.168.0.4"))
        self.pushButton_lian.setText(_translate("mainWindow", "连接中控"))
        self.label_17.setText(_translate("mainWindow", " 服务器地址"))
        self.lineEdit_4.setPlaceholderText(_translate("mainWindow", "192.168.0.88"))
        self.pushButton_duan.setText(_translate("mainWindow", "断开中控"))
        self.label_50.setText(_translate("mainWindow", "  读LOG地址:"))
        self.pushButton_shanchu.setText(_translate("mainWindow", " 删除LOG"))
        self.pushButton_xieru.setText(_translate("mainWindow", " 写入LOG"))
        self.label_57.setText(_translate("mainWindow", "           写入LOG:"))
        self.label_7.setText(_translate("mainWindow", "USB号"))
        self.comboBox.setItemText(0, _translate("mainWindow", "01"))
        self.comboBox.setItemText(1, _translate("mainWindow", "00"))
        self.comboBox.setItemText(2, _translate("mainWindow", "02"))
        self.label_8.setText(_translate("mainWindow", "上次测试工站"))
        self.comboBox_2.setItemText(0, _translate("mainWindow", "000"))
        self.comboBox_2.setItemText(1, _translate("mainWindow", "001"))
        self.comboBox_2.setItemText(2, _translate("mainWindow", "002"))
        self.comboBox_2.setItemText(3, _translate("mainWindow", "003"))
        self.comboBox_2.setItemText(4, _translate("mainWindow", "004"))
        self.label_9.setText(_translate("mainWindow", "本次测试工站"))
        self.comboBox_3.setItemText(0, _translate("mainWindow", "001"))
        self.comboBox_3.setItemText(1, _translate("mainWindow", "002"))
        self.comboBox_3.setItemText(2, _translate("mainWindow", "003"))
        self.comboBox_3.setItemText(3, _translate("mainWindow", "004"))
        self.label_10.setText(_translate("mainWindow", "PID号"))
        self.comboBox_4.setItemText(0, _translate("mainWindow", "0123456789AB"))
        self.comboBox_4.setItemText(1, _translate("mainWindow", "0235478916CD"))
        self.comboBox_4.setItemText(2, _translate("mainWindow", "88888888"))
        self.label_11.setText(_translate("mainWindow", "结果"))
        self.comboBox_5.setItemText(0, _translate("mainWindow", "OK"))
        self.comboBox_5.setItemText(1, _translate("mainWindow", "NG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "参数设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "使用帮助"))
        self.label.setText(_translate("mainWindow", "终端"))
        self.actiondakaipeizhiwenjian.setText(_translate("mainWindow", "查看配置文件内容(&L)"))
        self.actiondakaipeizhiwenjian_2.setText(_translate("mainWindow", "打开配置文件(&C)"))
        self.actionlianjixieshou_I.setText(_translate("mainWindow", "与机械手通讯(&I)"))
        self.actionlianjixieshou_I.setIconText(_translate("mainWindow", "与机械手通讯(I)"))
        self.actionlianjixieshou_I.setToolTip(_translate("mainWindow", "连接机械手(I)"))
        self.actionlianPlc_T.setText(_translate("mainWindow", "打开PLC串口(&T)"))
        self.actioncaozuoPLC_O.setText(_translate("mainWindow", "操作PLC(&O)"))
        self.actionCanshushezhi_P.setText(_translate("mainWindow", "参数设置(&P)"))
        self.actionjinzhi_N.setText(_translate("mainWindow", "禁止(&N)"))
        self.actionjinzhi_N.setIconText(_translate("mainWindow", "禁止(N)"))
        self.actionxunyu_Y.setText(_translate("mainWindow", "允许(&Y)"))
        self.actiondakaishujukufuwuqi.setText(_translate("mainWindow", "打开数据库服务器"))
        self.actionguanbishujukufuwuqi.setText(_translate("mainWindow", "关闭数据库服务器"))
        self.actionlianjieshujuku_L.setText(_translate("mainWindow", "连接数据库(&L)"))
        self.actionduankaishujuku_C.setText(_translate("mainWindow", "打开数据库(&C)"))
        self.actionpanduan_Y.setText(_translate("mainWindow", "判断(&Y)"))
        self.actionbupanduan_N.setText(_translate("mainWindow", "不判断(&N)"))
        self.actionyicitongguo_O.setText(_translate("mainWindow", "一次通过(&O)"))
        self.actionchankandangqianzhuangtai_S.setText(_translate("mainWindow", "查看当前状态(&S)"))
        self.actionjilu_R.setText(_translate("mainWindow", "记录(&R)"))
        self.actionshegnchengdejieguo_G.setText(_translate("mainWindow", "生成的结果(&G)"))
        self.actionpeizhicanshulujing_M.setText(_translate("mainWindow", "配置参数路径(&M)"))
        self.actionzhegnchangshenchan_N.setText(_translate("mainWindow", "正常生成(&N)"))
        self.actionshouliaomoshi_C.setText(_translate("mainWindow", "收料模式(&C)"))
        self.actionshi_Y.setText(_translate("mainWindow", "是(&Y)"))
        self.actionfou_N.setText(_translate("mainWindow", "否(&N)"))
        self.actionzhongkongjima_P.setText(_translate("mainWindow", "中控记码(&P)"))
        self.actionchongxinsaoma_I.setText(_translate("mainWindow", "重新扫码(&I)"))
        self.actionqiyong_U.setText(_translate("mainWindow", "启用(&U)"))
        self.actionjinyong_N.setText(_translate("mainWindow", "禁用(&N)"))
        self.actionchakanbangzhu_V.setText(_translate("mainWindow", "查看帮助(&V)"))
        self.actioncaozuojixies.setText(_translate("mainWindow", "操作机械手"))
        self.actionxunhuanjieshoujxs.setText(_translate("mainWindow", "循环接收JXS"))
        self.actionshoudongPLC.setText(_translate("mainWindow", "手动触发PLC"))
        self.actionmianbanxieru.setText(_translate("mainWindow", "面板信息写入"))
        self.actiondakaiwangkou.setText(_translate("mainWindow", "开启服务器"))
        self.actionwangkoufasong.setText(_translate("mainWindow", "网口发送"))
        self.actionjiechuPlc.setText(_translate("mainWindow", "解除PLC报警"))
import ico_rc
